### ISSUE TITLE
Sistem de salvare fisiere

### ISSUE THREAD

**Issue by BlastOfMihh** [ABC-practica-2024/Backend#10]
Vom avea nevoie de posibilitatea de a încărca, stoca și trimite fișiere pentru platformă, mai specific imagini și modele 3D. Se cere implementarea unui sistem care să permită acest lucru, iar fișierele să fie stocate pe disk și nu în baza de date (în DB vor fi stocate doar path-ul fișierelor). Se va folosi pentru pozele de profil, imagini cu artefacte și modele 3D ale acestora.

**Comment by dunmer0** [comment]
Am facut eu un FileService si am modificat si metoda de registration sa ia si o poza de profil. Clasa de FileService se poate folosi si adapta pentru toate use-case-urile. Este PR pe branchul de dev.

LE: Am facut eu deoarece s-a facut issue pe AUTH sa se poata puna poza de profil.
