### ISSUE TITLE
De reparat autorizarea de pe dev 

### ISSUE THREAD

**Issue by BlastOfMihh** [ABC-practica-2024/Backend#56]
Noi cat am lucrat pe dev arheo am avut rolurile outdated fata de cele de pe dev.
Autorizarea de pe endpointuri trebuie modificata astfel incat sa corespunda urmatorului enum de roluri:
public enum Role {
    ADMIN,
    ARHEO,
    LABWORKER,
    GUEST
}

**Comment by tibumanu** [comment]
PR #57
